### ISSUE TITLE
Errors come  when Training the model : transition_params is nan

### ISSUE THREAD

**Issue by jiangweisuc** [LopezGG/NN_NER_tensorFlow#1]
Errors come in  the network.py
============================================
        # CalculateMean cross-entropy loss
        with tf.name_scope("loss"):
            log_likelihood, self.transition_params = tf.contrib.crf.crf_log_likelihood(
                self.logits, self.input_y, self.sequence_lengths)
            self.loss = tf.reduce_mean(-log_likelihood,name="loss")
==================================================
the parametere "self.transition_params" is nan returned by function tf.contrib.crf.crf_log_likelihood

error details ::
InvalidArgumentError (see above for traceback): Nan in summary histogram for: transitions_0/grad/hist
	 [[Node: transitions_0/grad/hist = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](transitions_0/grad/hist/tag, gradients/AddN_4)]]
......

**Comment by LopezGG** [comment]
Thanks. Let me know into this during the weekend

**Comment by jiangweisuc** [comment]
Thanks you for your reply!

**Comment by jiangweisuc** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "C:\Program Files\Python3.5\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: transitions_0/grad/hist
	 [[Node: transitions_0/grad/hist = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](transitions_0/grad/hist/tag, gradients/AddN_4)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Python_Workspace/NN_NER_tensorFlow-master/BasicTextPreprocessing_CNN_CRF.py", line 335, in <module>
    train_step(sess,BiLSTM,FLAGS.PadZeroBegin,max_length,x_batch, y_batch,act_seq_lengths,FLAGS.dropout_keep_prob, embedd_table,char_batch,char_embedd_table)
  File "E:/Python_Workspace/NN_NER_tensorFlow-master/BasicTextPreprocessing_CNN_CRF.py", line 314, in train_step
    feed_dict=feed_dict)  #出错原因：transition_params 返回nan
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: transitions_0/grad/hist
	 [[Node: transitions_0/grad/hist = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](transitions_0/grad/hist/tag, gradients/AddN_4)]]

Caused by op 'transitions_0/grad/hist', defined at:
  File "E:/Python_Workspace/NN_NER_tensorFlow-master/BasicTextPreprocessing_CNN_CRF.py", line 253, in <module>
    grad_hist_summary = tf.summary.histogram("{}/grad/hist".format(v.name), grad_values)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\summary\summary.py", line 209, in histogram
    tag=scope.rstrip('/'), values=values, name=scope)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 139, in _histogram_summary
    name=name)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Program Files\Python3.5\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: transitions_0/grad/hist
	 [[Node: transitions_0/grad/hist = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](transitions_0/grad/hist/tag, gradients/AddN_4)]]

**Comment by LopezGG** [comment]
thanks for letting me know. Sorry could not look into this over the weekend !

**Comment by happy-nlp** [comment]
![image](https://user-images.githubusercontent.com/27487554/34308734-9ab0b234-e789-11e7-9834-682629ef2a98.png)
您好，我遇到这个NAN的问题，将学习率调至1E-10也不能解决

**Comment by happy-nlp** [comment]
@jiangweisuc 
你好，我也遇到了这个问题，而且调整学习率没有解决，你是怎么解决的？
Hello, I also met this problem, and the adjustment of learning rate has not been solved, how do you solve it?

**Comment by jiangweisuc** [comment]
@boo-boos ，我当时的情况是，问题出在程序提供的数据集上，因为程序里只提供了几句话，所以在计算batch 和batch count时，分母为0，所以造成在计算时learning rate 分母为0，故一直出差。把这个数据集换成完整的数据集便OK了，祝你好运。
Replace the reduced data set &nbsp;used in the program by the complete one，everything will be OK。
供参考

**Comment by happy-nlp** [comment]
@jiangweisuc 谢谢回复，这对我帮助太大了！请问哪里能下载到完整数据集，我看介绍里面没有写，能不能分享一份给我，感激不尽！

**Comment by jiangweisuc** [comment]
@boo-boos the data set is famous and public, so use Google or Baidu to download it.

**Comment by wenchengxucool** [comment]
> @boo-boos the data set is famous and public, so use Google or Baidu to download it.

您能提供一个数据集的名称吗？我们去搜一下。谢谢啦~
